"""check

Revision ID: 2cb9670e0de0
Revises: a4f61ec462b1
Create Date: 2024-03-17 19:05:52.726306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '2cb9670e0de0'
down_revision: Union[str, None] = 'a4f61ec462b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skilluserlink', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skilluserlink', 'level')
    # ### end Alembic commands ###
