"""skill delete level

Revision ID: 4f7dd7a1f0ce
Revises: 
Create Date: 2024-03-24 12:37:50.187729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7dd7a1f0ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'participant', name='role'),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'participant', name='role'),
               nullable=False)
    op.alter_column('user', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
